name: leetCode_dart
description: A sample command-line application.
version: 1.0.0


environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0